/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Vista;

import Controlador.ClienteController;
import Controlador.VehiculoController;
import Lists.clienteList;
import Lists.vehiculoList;
import java.awt.Dimension;




/**
 *
 * @author ilope
 */
public class FrmMain extends javax.swing.JFrame {
    private clienteList repoClientes;       // repositorio
    private FrmCliente frmCliente;  // formulario
    private ClienteController controllerClientes; // controlador
    private vehiculoList repoVehiculos;
    private FrmVehiculo frmVehiculo;
    private VehiculoController controllerVehiculos;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
        repoClientes = new clienteList();
        frmCliente = new FrmCliente();
        controllerClientes = new ClienteController(frmCliente, repoClientes);

        // Vehículos
        repoVehiculos = new vehiculoList();
        frmVehiculo = new FrmVehiculo();
        controllerVehiculos = new VehiculoController(repoVehiculos, frmVehiculo);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Control y Alquiler de Vehículos");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 60, 1980, 120);

        btnClientes.setText("jButton1");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnClientes);
        btnClientes.setBounds(570, 890, 140, 100);

        btnVehiculos.setText("jButton2");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnVehiculos);
        btnVehiculos.setBounds(750, 890, 130, 100);

        jButton3.setText("jButton3");
        jDesktopPane1.add(jButton3);
        jButton3.setBounds(920, 890, 130, 100);

        jButton4.setText("jButton4");
        jDesktopPane1.add(jButton4);
        jButton4.setBounds(1090, 890, 140, 100);

        jButton5.setText("jButton5");
        jDesktopPane1.add(jButton5);
        jButton5.setBounds(1260, 890, 130, 100);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1980, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    /**
     * Exit the Application
     */
    private void abrirInternal(javax.swing.JInternalFrame f) {
    jDesktopPane1.add(f);
    f.setVisible(true);
    try {
        f.setIcon(false);
        f.setMaximum(false);   // por si estaba max
        f.setSelected(true);
    } catch (Exception ignore) {}

    // centrar
    Dimension d = jDesktopPane1.getSize();
    f.setLocation((d.width - f.getWidth())/2, (d.height - f.getHeight())/2);
    f.toFront();
}
    
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
         abrirInternal(frmCliente);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        abrirInternal(frmVehiculo);
    }//GEN-LAST:event_btnVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(null,
        "Error al aplicar Look&Feel: " + e.getMessage(),
        "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
